__title__ = 'aec_correction'
__version__ = '1.0.0'
__author__ = 'Weijie Zhang'
__author_email__ = 'wzhang@bgc-jena.mpg.de'
__license__ = 'GNU GPLv3'
__copyright__ = 'Copyright 2024 by Weijie Zhang, MPI-BGC-GDM'